name: "µfmt"
description: "Validate formatting and import sorting"
inputs:
  path:
    description: "Paths to check"
    required: true
  version:
    description: "µfmt version to install"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Install µfmt
      if: ${{ inputs.version == 'latest' }}
      run: python -m pip install ufmt
      shell: bash
    - name: Install µfmt ${{ inputs.version }}
      if: ${{ inputs.version != 'latest' }}
      run: python -m pip install "ufmt==${{ inputs.version }}"
      shell: bash
    - name: Check formatting
      run: ufmt check ${{ inputs.path }}
      shell: bash
